# 2.行列積

以下のような行列A、Bを考えます。


A = $\displaystyle \left(\begin{array}{ccc} -1 & 2 & 3\\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{array}\right),B = \left(\begin{array}{ccc} 0 & 2 & 1\\ 0 & 2 & -8 \\ 2 & 9 & -1 \\ \end{array}\right)$

NumPyで表すと次のようになります。

In [99]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

### <span style="color: blue;">【答え】 </span>

以下に計算過程を示す

AB = $\displaystyle \left(\begin{array}{ccc} a & b & c\\ d & e & f \\ g & h & i \\ \end{array}\right)$ と定義すると、各行列値の計算は以下のようになる。


a = (-1) × 0 + 2 × 0 + 3 × 2

b = (-1) × 2 + 2 × 2 + 3 × 9

c = (-1) × 1 + 2 × (-8) + 3 × (-1)

d = 4 × 0 + (-5) × 0 + 6 × 2

e = 4 × 2 + (-5) × 2 + 6 × 9

f = 4 × 1 + (-5) × (-8) + 6 × (-1)

g = 7 × 0 + 8 × 0 + (-9) × 2

h = 7 × 2 + 8 × 2 + (-9) × 9

i = 7 × 1 + 8 × (-8) + (-9) × (-1)

よって、

AB = $\displaystyle \left(\begin{array}{ccc} 6 & 29 & -20\\ 12 & 52 & 38 \\ -18 & -51 & -48 \\ \end{array}\right)$ 


## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

In [100]:
# np.matmul()
print("np.matmul()：\n{}".format(np.matmul(a_ndarray, b_ndarray)))

print()
# np.dot()
print("np.dot()：\n{}".format(np.dot(a_ndarray, b_ndarray)))

print()
# @演算子
print("np.dot()：\n{}".format(a_ndarray @ b_ndarray))


np.matmul()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

np.dot()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]

np.dot()：
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 3.行列積のスクラッチ実装

## 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。
<br>

<ol>
    <li>行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる</li>
    <li>行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる</li>
    <li>行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる</li>
    <li>それらの値を全て足し合わせる</li>
</ol>


数式で表すと

　　　　　　　　　　　　　　　　　　　　　　　　$\displaystyle \sum_{k=0}^{2}a_{0, k}b_{0, k}$  

です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [101]:
k = a_ndarray.shape[0]
ans = 0

for i in range(k):
    ans += a_ndarray[0][i] * b_ndarray[i][0]

print("行列Aの0行目と行列Bの0列目の積和は {} です".format(ans))

行列Aの0行目と行列Bの0列目の積和は 6 です


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。



for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。

インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

In [102]:
def compute_inner_product(A, B):
    """
    行列ABの内積を計算する関数です。
    
    ＜引数＞
        A：ndarray
        B：ndarray
    
    ＜内部変数＞
        n: 行列Aの行数
        m: 行列Bの列数

        array：返り値

    """
    n = A.shape[0]
    m = B.shape[1]
    
    array = np.zeros((n, m))
    
    for row in range(n):
        for col in range(m):
            c = 0
            for i in range(n):
                c += A[row][i] * B[i][col]
        
            array[row][col] = c
        
    return array

print(compute_inner_product(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 4.行列積が定義されない組み合わせの行列

次に以下のような行列A、Bを考えます。


D = $\displaystyle \left(\begin{array}{ccc} -1 & 2 & 3\\ 4 & -5 & 6 \end{array}\right),E = \left(\begin{array}{ccc} -9 & 8 & 7\\ 6 & -5 & 4 \\\end{array}\right)$

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

In [103]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [104]:
def compute_inner_product_after(A, B):
    """
    行列ABの内積を計算する関数です。
    A
    
    ＜引数＞
        A：ndarray
        B：ndarray
    
    ＜内部変数＞
        A_n: 行列Aの行数
        A_m: 行列Aの列数
        B_n: 行列Bの行数
        B_m: 行列Bの列数

        array：返り値

    """
    A_n, A_m = A.shape
    B_n, B_m = B.shape
    
    if A_m != B_n:
        return print("{}行 {}列と{}行 {}列の行列の内積の計算はできません".format(A_n, A_m, B_n, B_m ))
        
    array = np.zeros((A_n, B_m))
    
    for row in range(A_n):
        for col in range(B_m):
            c = 0
            for i in range(A_n):
                c += A[row][i] * B[i][col]
        
            array[row][col] = c
        
    return array

print(compute_inner_product_after(d_ndarray, e_ndarray))

2行 3列と2行 3列の行列の内積の計算はできません
None


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [105]:
#np.transpose() を用いるパターン
print(d_ndarray @ np.transpose(e_ndarray))

print()

#.T を用いるパターン
print(d_ndarray @ e_ndarray.T)

[[ 46  -4]
 [-34  73]]

[[ 46  -4]
 [-34  73]]
